### ISSUE TITLE
Address logging test failures

### ISSUE THREAD

**Issue by khaeru** [iiasa/message-ix-models#173] opened 2024-04-17 08:14 UTC
@glatterf42 noticed test failures such as [these](https://github.com/iiasa/message-ix-models/actions/runs/8716589903/job/23914560827#step:9:10078) occurring on scheduled runs, starting today.

Symptoms:

- In general, the Pytest `caplog` fixture fails to capture certain messages, so the test assertions that check for those messages end up failing.
- Failures include:
  - Sometimes only util/test_cache.py::test_cached
  - Sometimes a longer list of 13 tests. When this occurs, they seem to all occur on the same pytest-xdist worker such as "gw1".
- All *-latest-py3.12-upstream-* jobs, both main and 3.8.0.

Actions to take:
- @khaeru to open a debugging PR and investigate if recent changes (esp #156) interfere destructively with pytest and/or recent pyam/ixmp4 releases.
- If necessary, we open a mitigation PR to skip or xfail some or all of these tests so that scheduled and PR CI can pass.

**Comment by glatterf42** [comment] 2024-04-17 08:42
I was able to reproduce the case with just one test failure locally. However, when I tried running this test again with debug output and alone (via `pytest --lf`), it passed.

**Comment by khaeru** [comment] 2024-04-18 07:48
I've tried the following:

(1) Run `watchexec -e py -- "pytest -k 'test_report or test_cache' -xv -rA"`. This runs 4 tests:

- PASSED test_report.py::test_register
- PASSED test_report.py::test_report_bare_res
- PASSED test_report.py::test_report_deprecated
- FAILED test_report.py::test_report_legacy

(2) Add a debugging function in test_report.py, roughly like this:
```py
def show_log_handlers(id: int):
    import logging

    from icecream import ic

    root_logger = logging.getLogger("root")

    ic(id, root_logger.level, root_logger.handlers)
```

(3) Added calls to this function in each of the 4 tests: at least at the top and bottom, or maybe in more places.

This gives the following results (abbreviated):
```
_____________________________________________ test_register ______________________________________________
------------------------------------------ Captured stderr call ------------------------------------------
ic| id: 'test_register 0'                                                                                 
    root_logger.level: 10                                                                                 
    root_logger.handlers: [<QueueHandler (NOTSET)>,                                                       
                           <_LiveLoggingNullHandler (NOTSET)>,                                            
                           <_FileHandler /dev/null (NOTSET)>,                                             
                           <LogCaptureHandler (NOTSET)>,     
                           <LogCaptureHandler (NOTSET)>]                                                  
ic| id: 'test_register 1'                                                                                 
    root_logger.level: 10                                                                                 
    root_logger.handlers: [<QueueHandler (NOTSET)>,                                                                                  <_LiveLoggingNullHandler (NOTSET)>,                                            
                           <_FileHandler /dev/null (NOTSET)>,                                             
                           <LogCaptureHandler (NOTSET)>,                                                  
                           <LogCaptureHandler (NOTSET)>]                                                  
__________________________________________ test_report_bare_res __________________________________________
------------------------------------------ Captured stderr call ------------------------------------------
ic| id: 'test_report_bare_res 0'
    root_logger.level: 10
    root_logger.handlers: [<QueueHandler (NOTSET)>,
                           <_LiveLoggingNullHandler (NOTSET)>,
                           <_FileHandler /dev/null (NOTSET)>,
                           <LogCaptureHandler (NOTSET)>,
                           <LogCaptureHandler (NOTSET)>]
ic| id: 'test_report_bare_res 1'
    root_logger.level: 0
    root_logger.handlers: []
_________________________________________ test_report_deprecated _________________________________________
------------------------------------------ Captured stderr call ------------------------------------------
ic| id: 'test_report_deprecated 0'
    root_logger.level: 0
    root_logger.handlers: [<LogCaptureHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
ic| id: 'test_report_deprecated 1'
    root_logger.level: 0
    root_logger.handlers: [<LogCaptureHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
___________________________________________ test_report_legacy ___________________________________________
------------------------------------------ Captured stderr call --------------------------------
ic| id: 0
    root_logger.level: 0
    root_logger.handlers: [<LogCaptureHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
ic| id: 1
    root_logger.level: 0
    root_logger.handlers: [<LogCaptureHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
ic| id: 2
    root_logger.level: 0
    root_logger.handlers: [<LogCaptureHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
```

So this tells me it is somewhere between the points "test_report_bare_res 0" and "test_report_bare_res 1" where the message-ix-models handlers get wiped out.

I'll continue to debug along these lines.

**Comment by khaeru** [comment] 2024-04-18 07:58
I expand the debugging function:
```python
def show_log_handlers(id: str, expected_n_handlers: int):
    import logging

    from icecream import ic

    root_logger = logging.getLogger("root")

    ic(id)

    if expected_n_handlers != len(root_logger.handlers):
        ic(
            root_logger.level,
            root_logger.handlers,
            root_logger.manager.loggerDict,
        )
        assert False
```

And put the following at the top of the one test:
```python
def test_report_bare_res(request, tmp_path, test_context):
    ...
    show_log_handlers("test_report_bare_res 0", 5)

    from importlib import import_module

    for name in (
        "dotenv",
        "fastapi",
        "fsspec",
        "hpack",
        "httpcore",
        "httpx",
        "matplotlib",
        "numba",
        "pint",
        "pycountry",
        "requests",
        "rich",
        "sdmx",
        "sqlalchemy",
        "tqdm",
        "urllib3",
        "xarray",
        "ixmp4",
        "pyam",
    ):
        import_module(name)
        show_log_handlers(f"test_report_bare_res after `import {name}`", 5)
```

Now I run with `watchexec -e py -- "pytest -k 'test_report_bare_res' -xv -rA"` and see output like:
```
ic| id: 'test_report_bare_res 0'                                                                                                                                                      
ic| id: 'test_report_bare_res after `import dotenv`'                                                                                                                                  
ic| id: 'test_report_bare_res after `import fastapi`'                                                                                                                                 
ic| id: 'test_report_bare_res after `import fsspec`'                                                                                                                                  
ic| id: 'test_report_bare_res after `import hpack`'                                                                                                                                   
ic| id: 'test_report_bare_res after `import httpcore`'                                                                                                                                
ic| id: 'test_report_bare_res after `import httpx`'                                                                                                                                   
ic| id: 'test_report_bare_res after `import matplotlib`'                                                                                                                              
ic| id: 'test_report_bare_res after `import numba`'                                                                                                                                   
ic| id: 'test_report_bare_res after `import pint`'                                                                                                                                    
ic| id: 'test_report_bare_res after `import pycountry`'                                                                                                                               
ic| id: 'test_report_bare_res after `import requests`'                                                                                                                                
ic| id: 'test_report_bare_res after `import rich`'                                                                                                                                    
ic| id: 'test_report_bare_res after `import sdmx`'                                                                                                                                    
ic| id: 'test_report_bare_res after `import sqlalchemy`'                                                                                                                              
ic| id: 'test_report_bare_res after `import tqdm`'                                                                                                                                    
ic| id: 'test_report_bare_res after `import urllib3`'                                                                                                                                 
ic| id: 'test_report_bare_res after `import xarray`'                                                                                                                                  
ic| id: 'test_report_bare_res after `import ixmp4`'                                                                                                                                   
ic| root_logger.level: 0                                                                                                                                                              
    root_logger.handlers: []                                                                                                                                                          
    root_logger.manager.loggerDict: {'PIL': <Logger PIL (INFO)>,
    ...
```
This indicates that the root logger's handlers are only wiped out by/as of the import of `ixmp4`. The prior import of all the other packages appearing in the list of loggers (shared above) does not to seem to trigger the same change.

**Comment by glatterf42** [comment] 2024-04-18 11:55
Both of them are configuring their logging via `logging.config.FileConfig`, which has a Warning at the bottom of [this section](https://docs.python.org/3/howto/logging.html#configuring-logging): if one doesn't set `disable_existing_loggers` to `False`, potentially all non-root loggers will be disabled. Oddly enough, both pyam and ixmp4 set this to `False`, though.

**Comment by glatterf42** [comment] 2024-04-18 12:00
There's also a warning at the bottom of [this section](https://docs.pytest.org/en/latest/how-to/logging.html#caplog-fixture) which might be relevant: if the root logger is modified during a test, the pytest.caplog handler may be removed, causing no logs to be captured.

**Comment by glatterf42** [comment] 2024-04-18 12:01
Both pyam and ixmp4 do something to the root logger which almost looks like clearing it: https://github.com/IAMconsortium/pyam/blob/main/pyam/logging.conf
I don't know if they actually need to do that.

**Comment by khaeru** [comment] 2024-04-18 12:53
> if one doesn't set `disable_existing_loggers` to `False`, potentially all non-root loggers will be disabled. Oddly enough, both pyam and ixmp4 set this to `False`, though.

Keep in mind the issue we are seeing is not with *Logger* instances, but with *Handler* instances. The logging docs are, unfortunately, both verbose and also silent on a lot of points, including I think what happens to handlers.

> if the root logger is modified during a test, the pytest.caplog handler may be removed, causing no logs to be captured.

This is the reason I wound up with code like this in message-ix-models:
https://github.com/iiasa/message-ix-models/blob/4378be615ba4b6e21868a32038c3e452fc73cded/message_ix_models/util/_logging.py#L256-L258
and
https://github.com/iiasa/message-ix-models/blob/4378be615ba4b6e21868a32038c3e452fc73cded/message_ix_models/util/_logging.py#L213

To wit: message-ix-models looks for an instance of *its own* QueueHandler class, and if it is not there, adds it. It ignores other handlers (e.g. the Pytest ones), and does not remove or replace them. I tried but could not get this to work with `logging.config.dictConfig`.

I suspect by placing something like `show_log_handlers()` above and below the ixmp4 and/or pyam calls to `logging.config.fileConfig()`, we could confirm that it is this built-in function, used in this way, that wipes out the existing handlers.

**Comment by glatterf42** [comment] 2024-04-18 14:10
I've added the first version of `show_log_handlers()` immediately before and after the `FileConfig` call in ixmp4:
```python
        show_log_handlers(0)
        logging.config.fileConfig(logging_config, disable_existing_loggers=False)
        show_log_handlers(1)
```
And with that, I see:
```bash
ic| id: 'test_report_bare_res after `import xarray`'
ic| id: 0
    root_logger.level: 10
    root_logger.handlers: [<QueueHandler (NOTSET)>,
                           <_LiveLoggingNullHandler (NOTSET)>,
                           <_FileHandler /dev/null (NOTSET)>,
                           <LogCaptureHandler (NOTSET)>,
                           <LogCaptureHandler (NOTSET)>]
ic| id: 1, root_logger.level: 0, root_logger.handlers: []
ic| id: 'test_report_bare_res after `import ixmp4`'
ic| root_logger.level: 0
    root_logger.handlers: []
    root_logger.manager.loggerDict: {'PIL': <Logger PIL (INFO)>,
```

So it seems this function is indeed responsible for wiping out the handlers.

**Comment by glatterf42** [comment] 2024-04-18 14:14
According to [their docs](https://docs.python.org/3/library/logging.config.html#logging-config-fileformat) using `FileConfig` is older than `DictConfig` and one should prefer the latter. Also according to their docs, the config file _must_ set `level` and `handlers` for `root_logger`, but the `DictConfig` only requires a `version` key. So maybe by migrating to `DictConfig`, we can avoid overwriting the root logger('s handlers).

**Comment by glatterf42** [comment] 2024-04-18 16:13
I found a solution, the test is working fine again locally. We won't need to change anything if we can get the PRs I'm going to push to ixmp4 and pyam merged reasonably fast. Otherwise, we could use their branches. I'll push these tomorrow.

**Comment by glatterf42** [comment] 2024-04-19 08:13
I released a new version of ixmp4 that should include a fix, I don't yet know when pyam can follow suit. If we use their main-branch version, we should already be able to get a fix from them as well.

**Comment by khaeru** [comment] 2024-04-19 08:17
Great! Could you please trial those adjustments on the #175 branch, when you have a chance?

**Comment by glatterf42** [comment] 2024-04-19 09:21
Not sure what's up with the coverage report, but the fixes work :)

**Closed** 2024-04-22 07:47 UTC

**Comment by khaeru** [comment] 2024-04-22 07:54
Glad to see that new pyam and ixmp4 releases have addressed this!

In the future, on the off chance that message-ix-models users encounter issues with logging behaviour, we should keep in mind to check whether they are using the affected versions and remind them to upgrade.
